@startuml
start

:Користувач входить у систему;
if (Успішна аутентифікація?) then (Так)
    :Система відображає список виборів;
    :Користувач обирає вибори;
    :Система відображає список кандидатів;
    if (Користувач вже голосував?) then (Так)
        :Відображається повідомлення "Ви вже проголосували";
    else (Ні)
        :Користувач обирає кандидата;
        :Голос зберігається у базі даних;
        :Відображається підтвердження голосування;
    endif
else (Ні)
    :Відображається помилка входу;
endif

stop
@enduml